<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="three_arm_robot">
  <!-- Properties -->
  <xacro:property name="link_length" value="1.0"/> <!-- Length of each arm -->
  <xacro:property name="link_width" value="0.1"/> <!-- Width of each arm -->
  <xacro:property name="joint_limit" value="1.5708"/> <!-- 90 degrees -->
  <xacro:property name="base_radius" value="0.1"/> <!-- Radius of the base -->
  <xacro:property name="base_height" value="0.2"/> <!-- Height of the base -->

  <!-- Base Link -->
  <link name="base_link">
    <visual>
      <geometry>
        <cylinder length="${base_height}" radius="${base_radius}"/>
      </geometry>
      <material name="black"/>
    </visual>
    <collision>
      <geometry>
        <cylinder length="${base_height}" radius="${base_radius}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="1.0"/>
      <origin xyz="0 0 0"/>
      <inertia ixx="0.01" ixy="0" ixz="0" iyy="0.01" iyz="0" izz="0.01"/>
    </inertial>
  </link>

  <!-- Joint 1 -->
  <joint name="joint1" type="revolute">
    <parent link="base_link"/>
    <child link="link1"/>
    <origin xyz="0 0 ${base_height / 2}" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit lower="-${joint_limit}" upper="${joint_limit}" effort="1.0" velocity="1.0"/>
  </joint>

  <!-- Link 1 -->
  <link name="link1">
    <visual>
      <geometry>
        <box size="${link_length} ${link_width} ${link_width}"/>
      </geometry>
      <material name="blue"/>
    </visual>
    <collision>
      <geometry>
        <box size="${link_length} ${link_width} ${link_width}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="1.0"/>
      <origin xyz="${link_length / 2} 0 0"/>
      <inertia ixx="0.01" ixy="0" ixz="0" iyy="0.01" iyz="0" izz="0.01"/>
    </inertial>
  </link>

    <!-- Joint 2 -->
    <joint name="joint2" type="revolute">
      <parent link="link1"/>
      <child link="link2"/>
      <origin xyz="${link_length} 0 0" rpy="0 0 0"/>
      <axis xyz="0 0 1"/>
      <limit lower="-${joint_limit}" upper="${joint_limit}" effort="1.0" velocity="1.0"/>
    </joint>

    <!-- Link 2 -->
    <link name="link2">
      <visual>
        <geometry>
          <box size="${link_length} ${link_width} ${link_width}"/>
        </geometry>
        <material name="green"/>
      </visual>
      <collision>
        <geometry>
          <box size="${link_length} ${link_width} ${link_width}"/>
        </geometry>
      </collision>
      <inertial>
        <mass value="1.0"/>
        <origin xyz="${link_length / 2} 0 0"/>
        <inertia ixx="0.01" ixy="0" ixz="0" iyy="0.01" iyz="0" izz="0.01"/>
      </inertial>
    </link>

    <!-- Joint 3 -->
    <joint name="joint3" type="revolute">
      <parent link="link2"/>
      <child link="link3"/>
      <origin xyz="${link_length} 0 0" rpy="0 0 0"/>
      <axis xyz="0 0 1"/>
      <limit lower="-${joint_limit}" upper="${joint_limit}" effort="1.0" velocity="1.0"/>
    </joint>

    <!-- Link 3 -->
    <link name="link3">
      <visual>
        <geometry>
          <box size="${link_length} ${link_width} ${link_width}"/>
        </geometry>
        <material name="red"/>
      </visual>
      <collision>
        <geometry>
          <box size="${link_length} ${link_width} ${link_width}"/>
        </geometry>
      </collision>
      <inertial>
        <mass value="1.0"/>
        <origin xyz="${link_length / 2} 0 0"/>
        <inertia ixx="0.01" ixy="0" ixz="0" iyy="0.01" iyz="0" izz="0.01"/>
      </inertial>
    </link>

</robot>
